default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: remember-the-bills_development

test:
  <<: *default
  database: remember-the-bills_test

production:
  <<: *default
  database: remember-the-bills_production
  username: remember-the-bills
  password: <%= ENV['REMEMBER-THE-BILLS_DATABASE_PASSWORD'] %>
